name: Development Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - test-2

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions

jobs:
  build:
    name: Windows x64

    runs-on: windows-2025

    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - name: Check out sources
        uses: actions/checkout@v6

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-x86_64-windows-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-x86_64-windows-

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: vcpkg.json

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: windows-x64

      - name: Configure
        run: >
          cmake
          --preset release-windows-x86_64
          -DENABLE_DEBUG_DEPS=OFF
          -DMELONDS_EMBED_BUILD_INFO=ON
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build melonDS
        run: >
          cmake
          --build build/release-windows-x86_64
          --parallel

      - name: Upload melonDS.exe
        uses: actions/upload-artifact@v7
        with:
          name: melonDS-windows-x64
          path: build/release-windows-x86_64/melonDS.exe

      - name: Save vcpkg cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-x86_64-windows-${{ hashFiles('vcpkg.json') }}
